"use strict";

// Generated by uniffi-bindgen-react-native

import { TurboModuleRegistry } from 'react-native';
export default TurboModuleRegistry.getEnforcing('MoproFfi');
//# sourceMappingURL=NativeMoproFfi.js.map